import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const robotFont = Roboto({
  weight: ["400", "800"],
  subsets: ["latin"],
  variable: "--font-roboto",
});


export const metadata: Metadata = {
  title: "Ignite Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
