import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { CartProvider } from "@/contexts/CartContext";
import CartDrawer from "@/components/CartDrawer";

const robotFont = Roboto({
  weight: ["400", "800"],
  subsets: ["latin"],
  variable: "--font-roboto",
});


export const metadata: Metadata = {
   title: {
    default: "Ignite Shop",
    template: "%s | Ignite Shop", // Permite que páginas filhas sobrescrevam
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotFont.variable} antialiased`}
      >
        <CartProvider>
          <Header />
          {children}
          <CartDrawer />
        </CartProvider>
      </body>
    </html>
  );
}
